### ISSUE TITLE
Error in send_object function with DateTime/DateTimeArray

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-rust#112]
The function `send_objects` does not accept the type chrono::DateTime<chrono::Utc>.
The compiler returns the following `error: the trait '_serde::Serialize' is not implemented for 'chrono::DateTime<Utc>'.`

**Comment by sorru94** [comment]
Adding the `serde` feature on `chrono` seems to partially fix this.
After the change when sending the value: `2022-08-29T17:46:48.000Z` for a `chrono::DateTime<chrono::Utc>` type, the following error is returned: `send error (You are sending the wrong type for this object mapping: got String("2022-08-29T17:46:48.000Z"), expected DateTime)`.

The issue then becomes quite similar to #111.
Related to the [to_document()](https://docs.rs/bson/latest/bson/fn.to_document.html) function in the `bson` library. Used here:
https://github.com/astarte-platform/astarte-device-sdk-rust/blob/8286c58a325ae0b4eddedb69c756e7a243ad7a77/src/lib.rs#L821-L831

When `data` is a struct containing a field as such:
```
AggregateStruct {
    datetime_element: 2023-01-19T17:46:36.921264162Z,
}
```
The resulting `doc` variable will be a `bson::Document` as such:
```
Document({
    "datetime_element": String(
        "2023-01-19T17:46:36.921264162Z",
    ),
})
```
