### ISSUE TITLE
Error in receive_object(poll) with BinaryBlob/BinaryBlobArray

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-rust#113]
When receiving an object with BinaryBlob, the device `poll returns: ReceiveError("You are receiving the wrong type for this object mapping").` 

Additional info:
Astarte POST request body (for an aggregate datastream) is: {"data":{...,"binaryblob_endpoint":"d29ybGQ=",...}}.

**Comment by sorru94** [comment]
NB: this issue is linked to: https://github.com/astarte-platform/astarte/issues/754.
