### ISSUE TITLE
Add restrictions on allowed chars in endpoint parameters

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte-device-sdk-rust#179]
The chars `/`, `+` and `#` should not be allowed in endpoint parameters.
This is due to MQTT specifications. As `+` and `#` are used as wildcards and `/` is used as a path separator.

**Comment by sorru94** [comment]
`/` is already covered by the following function.
https://github.com/astarte-platform/astarte-device-sdk-rust/blob/355fdd51d0db10161033593cf1d8a56392f8df17/src/interface/traits.rs#L71-L97
The other two chars should be added.

**Comment by joshuachp** [comment]
This was closed in #186
