### ISSUE TITLE
Add APIs to expose server-owned properties

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-rust#230]
It would be nice to have some APIs that expose the server-owned properties kept by the device.

examples:
1. `get_server_owned_property(interface, path)`
2. `get_all_server_owned_properties()`

**Comment by joshuachp** [comment]
The current get_property method doesn't differentiate between server-owned and device-owned properties. However, properties are already unique based on interface and path, so callers typically know the ownership.

To access all server/device properties efficiently, I've introduced a trait resembling `PropertyStor`e. This trait lets them be accessed from the SDK struct. Additionally, I've incorporated ownership into `StoredProperty` and stores for better value filtering based on ownership.
