### ISSUE TITLE
API Cleanup

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-device-sdk-rust#57]
- [ ] Rename `AstarteSdk` to `AstarteDeviceSdk`

**Comment by harlem88** [comment]
1. `ClientBoud` -> `AstarteDeviceData` or `AstarteDeviceDataEvent`
2. device `poll` function -> `astarte_device_data_event`

**Comment by FrancescoVaiani** [comment]
> 1. `ClientBoud` -> `AstarteDeviceData` or `AstarteDeviceDataEvent`

`ClientBound` -> `AstarteInboundMessage`

**Comment by FrancescoVaiani** [comment]
In `Cargo.roml`
`name = "astarte_sdk"` -> `name = "astarte-sdk"`

**Comment by harlem88** [comment]
> In `Cargo.roml` `name = "astarte_sdk"` -> `name = "astarte-sdk"`

or `astarte-device-sdk`
