### ISSUE TITLE
Improve Checks on Dynamic Introspection

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-rust#85]
At this time, if you add an interface that is already in introspection, it is replaced by the new one, without checking the major  or minor version.

We should improve checking in case of :
- `new major > old major` :  error should be raise (can't upgrade an interface major at runtime) ?
- `same major` : error should be raise (Interface already present in mapping) ? or simple warning ? 
- `same minor` : error should be raise (Interface already present in mapping) ? or simple warning ? 
- `new minor < old minor` : error should be raise (can't downgrade an interface at runtime)
- `new minor > old minor` : the new interface replaces the old one

**Comment by sorru94** [comment]
As a suggestion while resolving this issue evaluate if the struct `Interface` should be present in the public API of the SDK.
